[workspace.package]
version = "0.34.0-rc.1"
authors = ["Fastnear Inc <hello@fastnear.com>"]
edition = "2021"
repository = "https://github.com/fastnear/libs"
rust-version = "1.86.0"
license = "MIT OR Apache-2.0"

[workspace]
resolver = "2"
members = [
    "flat-state",
    "neardata-fetcher",
    "primitives"
]

[workspace.dependencies]
near-indexer-primitives = { git = "https://github.com/fastnear/nearcore", rev = "845760a2c5cb6a130f62386dc832bfc5be94728d" }
near-primitives = { git = "https://github.com/fastnear/nearcore", rev = "845760a2c5cb6a130f62386dc832bfc5be94728d" }
near-crypto = { git = "https://github.com/fastnear/nearcore", rev = "845760a2c5cb6a130f62386dc832bfc5be94728d" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_repr = "0.1"
serde_with = { version = "3.0", features = ["base64"] }
reqwest = { version = "0.12.2", features = ["json", "rustls-tls"] }
tokio = { version = "1", features = ["time", "sync", "rt-multi-thread"] }
tracing = { version = "0.1.13", features = ["log"] }
borsh = { version = "1.5.0", features = ["derive"] }
near-jsonrpc-client = "0.18"
near-jsonrpc-primitives = { git = "https://github.com/fastnear/nearcore", rev = "845760a2c5cb6a130f62386dc832bfc5be94728d" }
near-chain-configs = { git = "https://github.com/fastnear/nearcore", rev = "845760a2c5cb6a130f62386dc832bfc5be94728d" }
tar = "0.4.43"
flate2 = "1.0"
url = "2.5.4"

