use near_indexer_primitives::{
    IndexerChunkView, IndexerExecutionOutcomeWithReceipt, IndexerShard,
    IndexerTransactionWithOutcome, StreamerMessage,
};
use near_primitives::hash::CryptoHash;
use near_primitives::types::ShardId;
use near_primitives::views::{
    BlockView, ExecutionOutcomeWithIdView, ReceiptView, StateChangeWithCauseView,
};
use near_primitives::{types, views};

#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub struct BlockWithTxHashes {
    pub block: BlockView,
    pub shards: Vec<IndexerShardWithTxHashes>,
}

#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub struct IndexerChunkViewWithOptionalLocalReceipts {
    pub author: types::AccountId,
    pub header: views::ChunkHeaderView,
    pub transactions: Vec<IndexerTransactionWithOutcome>,
    /// Represents receipts generated by execution of the previous chunk.
    /// Note that those are not the receipts executed by this chunk or even
    /// targeting that shard.
    pub receipts: Vec<views::ReceiptView>,
    /// Receipts generated in this chunk from transactions with `signer_id`
    /// equal to `receiver_id`.
    #[serde(default)]
    pub local_receipts: Vec<views::ReceiptView>,
}

#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub struct IndexerShardWithTxHashes {
    pub shard_id: ShardId,
    pub chunk: Option<IndexerChunkViewWithOptionalLocalReceipts>,
    pub receipt_execution_outcomes: Vec<IndexerExecutionOutcomeWithReceiptAndTxHash>,
    pub state_changes: Vec<StateChangeWithCauseView>,
}

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct IndexerExecutionOutcomeWithReceiptAndTxHash {
    pub execution_outcome: ExecutionOutcomeWithIdView,
    pub receipt: ReceiptView,
    pub tx_hash: Option<CryptoHash>,
}

impl From<IndexerChunkView> for IndexerChunkViewWithOptionalLocalReceipts {
    fn from(chunk: IndexerChunkView) -> Self {
        Self {
            author: chunk.author,
            header: chunk.header,
            transactions: chunk.transactions,
            receipts: chunk.receipts,
            local_receipts: chunk.local_receipts,
        }
    }
}

impl From<StreamerMessage> for BlockWithTxHashes {
    fn from(streamer_message: StreamerMessage) -> Self {
        Self {
            block: streamer_message.block,
            shards: streamer_message
                .shards
                .into_iter()
                .map(
                    |IndexerShard {
                         shard_id,
                         chunk,
                         receipt_execution_outcomes,
                         state_changes,
                     }| IndexerShardWithTxHashes {
                        shard_id,
                        chunk: chunk.map(|c| c.into()),
                        receipt_execution_outcomes: receipt_execution_outcomes
                            .into_iter()
                            .map(
                                |IndexerExecutionOutcomeWithReceipt {
                                     execution_outcome,
                                     receipt,
                                 }| {
                                    IndexerExecutionOutcomeWithReceiptAndTxHash {
                                        execution_outcome,
                                        receipt,
                                        tx_hash: None,
                                    }
                                },
                            )
                            .collect(),
                        state_changes,
                    },
                )
                .collect(),
        }
    }
}
