[package]
name = "fastnear-flat-state"
description = "This crate provides a flat state that is being updated from the neardata.xyz"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish = true

[dependencies]
reqwest.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true
borsh.workspace = true
near-crypto.workspace = true

fastnear-primitives = { version = "0.0.3", path = "../primitives" }
fastnear-neardata-fetcher = { version = "0.0.3", path = "../neardata-fetcher" }

